<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handling</title>
</head>
<body>
    <script>

        //MEMBUAT CLASS ERROR MANUAL
        //=> walaupun JavaScript sudah memiliki standard class Error
        //namun alangkah baiknya kita membedakan tiap jenis error
        //=> untuk membuat error sendiri secara manual sangatlah mudah,
        //cukup membuat class turunan dari calass Error
        //=> dan jangan lupa tambahkan parameter message, agar bisa dikirim ke parameter
        // di constructor class Error
        class ValidationError extends Error {
            constructor(message, field) {
                super(message);
                this.field = field;
            }
        }
        //ERROR HANDLING
        //=> saat terjadi error di kode program JavaScript, kadang kita tidak ingin program kita berhenti,
        //di JavaScript, kita bisa menangkap jika terjadi error
        //=> kita bisa menggunakan try catch statement untuk menangkap error
        //=> pada block try, kita akan mencoba mengkases kode program yang bisa menyebabkan error
        //dan kika terjadi error, block try akan berhenti dan otomatis masuk ke block catch
        //=> jika tidak terjadi error, block catch tidak akan diekekusi

        class MathUtil {            
            static sum(...numbers) { //method
                if(numbers.length === 0) {
                throw new ValidationError("Total parameter harus lebih dari 0");
            }
                let total = 0;
                for (const number of numbers) {
                    total += number;
                }
                return total;
            }
        }

        try {
            console.info(MathUtil.sum());
            console.info("dika");
        } catch (error) {
            if(error instanceof ValidationError) {
                console.info(`Terjadi error di field ${error.field} dengan error : ${error.message}`);
            }else {
                console.info(`Terjadi error : ${error.message}`);
            }
        } finally {
            console.info("Program selesai (finally)");
        }

        //KATA KUNCI FINALLY
        //=> kadang kita ingin melakukan sesuatu entah itu terjadi error ataupun tidak
        //=> dalam try catch, kita bisa menambahkan block finally
        //=> block finally ini akan selalu dieksekusi setelah block try dan catch selesai
        //entah terjadi error atau tidak, block finally akan selalu dieksekusi

        console.info("kode ini tetep jalan");

        //TRY FINALLY
        //=> kata kunci finally juga bisa digunakan tanpa perlu mengguakan catch
        //=> biasanya ini digunakan dalam kasus tertentu

        class Counter {
            #counter = 0; //private field

            next() {
               try {
                   return this.#counter++;
               } finally {
                   this.#counter++;
               }
            }
        }

        const counter = new Counter();
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());
        console.info(counter.next());

    </script>
</body>
</html>